/**
 * @file github.js
 * @description Fetches and renders GitHub data
 * @author Sara Sjödin Scolari
 */
export async function fetchGitHub(query) {
  githubContainer.innerHTML = '';
}

const githubContainer = document.getElementById('github-data');

function extractCountryCode(location = '') {
  if (!location) return null;

  const lower = location.toLowerCase();
  if (lower.includes('sweden')) return 'se';
  if (lower.includes('usa') || lower.includes('united states')) return 'us';
  if (lower.includes('germany')) return 'de';
  if (lower.includes('japan')) return 'jp';
  if (lower.includes('france')) return 'fr';
  if (lower.includes('canada')) return 'ca';
  if (lower.includes('andorra')) return 'ad';
  if (lower.includes('united arab emirates') || lower.includes('uae'))
    return 'ae';
  if (lower.includes('afghanistan')) return 'af';
  if (lower.includes('antigua') || lower.includes('barbuda')) return 'ag';
  if (lower.includes('anguilla')) return 'ai';
  if (lower.includes('albania')) return 'al';
  if (lower.includes('armenia')) return 'am';
  if (lower.includes('angola')) return 'ao';
  if (lower.includes('antarctica')) return 'aq';
  if (lower.includes('argentina')) return 'ar';
  if (lower.includes('armenia')) return 'am';
  if (lower.includes('aruba')) return 'aw';
  if (lower.includes('australia')) return 'au';
  if (lower.includes('austria')) return 'at';
  if (lower.includes('azerbaijan')) return 'az';
  if (lower.includes('bahamas')) return 'bs';
  if (lower.includes('bahrain')) return 'bh';
  if (lower.includes('bangladesh')) return 'bd';
  if (lower.includes('barbados')) return 'bb';
  if (lower.includes('belarus')) return 'by';
  if (lower.includes('belgium')) return 'be';
  if (lower.includes('belize')) return 'bz';
  if (lower.includes('benin')) return 'bj';
  if (lower.includes('bermuda')) return 'bm';
  if (lower.includes('bhutan')) return 'bt';
  if (lower.includes('bolivia')) return 'bo';
  if (lower.includes('bosnia and herzegovina')) return 'ba';
  if (lower.includes('botswana')) return 'bw';
  if (lower.includes('brazil')) return 'br';
  if (lower.includes('brunei')) return 'bn';
  if (lower.includes('bulgaria')) return 'bg';
  if (lower.includes('burkina faso')) return 'bf';
  if (lower.includes('burundi')) return 'bi';
  if (lower.includes('cambodia')) return 'kh';
  if (lower.includes('cameroon')) return 'cm';
  if (lower.includes('canada')) return 'ca';
  if (lower.includes('cape verde')) return 'cv';
  if (lower.includes('central african republic')) return 'cf';
  if (lower.includes('chad')) return 'td';
  if (lower.includes('chile')) return 'cl';
  if (lower.includes('china')) return 'cn';
  if (lower.includes('colombia')) return 'co';
  if (lower.includes('comoros')) return 'km';
  if (lower.includes('congo')) return 'cg';
  if (lower.includes('democratic republic of the congo')) return 'cd';
  if (lower.includes('costa rica')) return 'cr';
  if (lower.includes('croatia')) return 'hr';
  if (lower.includes('cuba')) return 'cu';
  if (lower.includes('cyprus')) return 'cy';
  if (lower.includes('czech republic')) return 'cz';
  if (lower.includes('denmark')) return 'dk';
  if (lower.includes('djibouti')) return 'dj';
  if (lower.includes('dominica')) return 'dm';
  if (lower.includes('dominican republic')) return 'do';
  if (lower.includes('ecuador')) return 'ec';
  if (lower.includes('egypt')) return 'eg';
  if (lower.includes('el salvador')) return 'sv';
  if (lower.includes('equatorial guinea')) return 'gq';
  if (lower.includes('eritrea')) return 'er';
  if (lower.includes('estonia')) return 'ee';
  if (lower.includes('ethiopia')) return 'et';
  if (lower.includes('fiji')) return 'fj';
  if (lower.includes('finland')) return 'fi';
  if (lower.includes('france')) return 'fr';
  if (lower.includes('gabon')) return 'ga';
  if (lower.includes('gambia')) return 'gm';
  if (lower.includes('georgia')) return 'ge';
  if (lower.includes('germany')) return 'de';
  if (lower.includes('ghana')) return 'gh';
  if (lower.includes('greece')) return 'gr';
  if (lower.includes('grenada')) return 'gd';
  if (lower.includes('guatemala')) return 'gt';
  if (lower.includes('guinea')) return 'gn';
  if (lower.includes('guinea-bissau')) return 'gw';
  if (lower.includes('guyana')) return 'gy';
  if (lower.includes('haiti')) return 'ht';
  if (lower.includes('honduras')) return 'hn';
  if (lower.includes('hungary')) return 'hu';
  if (lower.includes('iceland')) return 'is';
  if (lower.includes('india')) return 'in';
  if (lower.includes('indonesia')) return 'id';
  if (lower.includes('iran')) return 'ir';
  if (lower.includes('iraq')) return 'iq';
  if (lower.includes('ireland')) return 'ie';
  if (lower.includes('israel')) return 'il';
  if (lower.includes('italy')) return 'it';
  if (lower.includes('jamaica')) return 'jm';
  if (lower.includes('japan')) return 'jp';
  if (lower.includes('jordan')) return 'jo';
  if (lower.includes('kazakhstan')) return 'kz';
  if (lower.includes('kenya')) return 'ke';
  if (lower.includes('kiribati')) return 'ki';
  if (lower.includes('kuwait')) return 'kw';
  if (lower.includes('kyrgyzstan')) return 'kg';
  if (lower.includes('laos')) return 'la';
  if (lower.includes('latvia')) return 'lv';
  if (lower.includes('lebanon')) return 'lb';
  if (lower.includes('lesotho')) return 'ls';
  if (lower.includes('liberia')) return 'lr';
  if (lower.includes('libya')) return 'ly';
  if (lower.includes('liechtenstein')) return 'li';
  if (lower.includes('lithuania')) return 'lt';
  if (lower.includes('luxembourg')) return 'lu';
  if (lower.includes('north macedonia')) return 'mk';
  if (lower.includes('madagascar')) return 'mg';
  if (lower.includes('malawi')) return 'mw';
  if (lower.includes('malaysia')) return 'my';
  if (lower.includes('maldives')) return 'mv';
  if (lower.includes('mali')) return 'ml';
  if (lower.includes('malta')) return 'mt';
  if (lower.includes('marshall islands')) return 'mh';
  if (lower.includes('mauritania')) return 'mr';
  if (lower.includes('mauritius')) return 'mu';
  if (lower.includes('mexico')) return 'mx';
  if (lower.includes('micronesia')) return 'fm';
  if (lower.includes('moldova')) return 'md';
  if (lower.includes('monaco')) return 'mc';
  if (lower.includes('mongolia')) return 'mn';
  if (lower.includes('montenegro')) return 'me';
  if (lower.includes('morocco')) return 'ma';
  if (lower.includes('mozambique')) return 'mz';
  if (lower.includes('myanmar')) return 'mm';
  if (lower.includes('namibia')) return 'na';
  if (lower.includes('nauru')) return 'nr';
  if (lower.includes('nepal')) return 'np';
  if (lower.includes('netherlands')) return 'nl';
  if (lower.includes('new zealand')) return 'nz';
  if (lower.includes('nicaragua')) return 'ni';
  if (lower.includes('niger')) return 'ne';
  if (lower.includes('nigeria')) return 'ng';
  if (lower.includes('norway')) return 'no';
  if (lower.includes('oman')) return 'om';
  if (lower.includes('pakistan')) return 'pk';
  if (lower.includes('palau')) return 'pw';
  if (lower.includes('panama')) return 'pa';
  if (lower.includes('papua new guinea')) return 'pg';
  if (lower.includes('paraguay')) return 'py';
  if (lower.includes('peru')) return 'pe';
  if (lower.includes('philippines')) return 'ph';
  if (lower.includes('poland')) return 'pl';
  if (lower.includes('portugal')) return 'pt';
  if (lower.includes('qatar')) return 'qa';
  if (lower.includes('romania')) return 'ro';
  if (lower.includes('russia')) return 'ru';
  if (lower.includes('rwanda')) return 'rw';
  if (lower.includes('saint kitts and nevis')) return 'kn';
  if (lower.includes('saint lucia')) return 'lc';
  if (lower.includes('saint vincent and the grenadines')) return 'vc';
  if (lower.includes('samoa')) return 'ws';
  if (lower.includes('san marino')) return 'sm';
  if (lower.includes('sao tome and principe')) return 'st';
  if (lower.includes('saudi arabia')) return 'sa';
  if (lower.includes('senegal')) return 'sn';
  if (lower.includes('serbia')) return 'rs';
  if (lower.includes('seychelles')) return 'sc';
  if (lower.includes('sierra leone')) return 'sl';
  if (lower.includes('singapore')) return 'sg';
  if (lower.includes('slovakia')) return 'sk';
  if (lower.includes('slovenia')) return 'si';
  if (lower.includes('solomon islands')) return 'sb';
  if (lower.includes('somalia')) return 'so';
  if (lower.includes('south africa')) return 'za';
  if (lower.includes('south korea')) return 'kr';
  if (lower.includes('south sudan')) return 'ss';
  if (lower.includes('spain')) return 'es';
  if (lower.includes('sri lanka')) return 'lk';
  if (lower.includes('sudan')) return 'sd';
  if (lower.includes('suriname')) return 'sr';
  if (lower.includes('eswatini')) return 'sz';
  if (lower.includes('sweden')) return 'se';
  if (lower.includes('switzerland')) return 'ch';
  if (lower.includes('syria')) return 'sy';
  if (lower.includes('taiwan')) return 'tw';
  if (lower.includes('tajikistan')) return 'tj';
  if (lower.includes('tanzania')) return 'tz';
  if (lower.includes('thailand')) return 'th';
  if (lower.includes('timor-leste')) return 'tl';
  if (lower.includes('togo')) return 'tg';
  if (lower.includes('tonga')) return 'to';
  if (lower.includes('trinidad and tobago')) return 'tt';
  if (lower.includes('tunisia')) return 'tn';
  if (lower.includes('turkey')) return 'tr';
  if (lower.includes('turkmenistan')) return 'tm';
  if (lower.includes('tuvalu')) return 'tv';
  if (lower.includes('uganda')) return 'ug';
  if (lower.includes('ukraine')) return 'ua';
  if (lower.includes('united arab emirates')) return 'ae';
  if (lower.includes('united kingdom')) return 'gb';
  if (lower.includes('united states')) return 'us';
  if (lower.includes('uruguay')) return 'uy';
  if (lower.includes('uzbekistan')) return 'uz';
  if (lower.includes('vanuatu')) return 'vu';
  if (lower.includes('venezuela')) return 've';
  if (lower.includes('vietnam')) return 'vn';
  if (lower.includes('yemen')) return 'ye';
  if (lower.includes('zambia')) return 'zm';
  if (lower.includes('zimbabwe')) return 'zw';
  return null;
}
